# DEEP LEARNING
## TUẦN 2: NUMPY, PANDAS, MATPLOTLIB

In [2]:
# Numpy là thư viện kiểu list
# Vì:
# + numpy nhanh 
# + có nhiều hàm tích hợp dễ sử dụng cho AI
# để sử dụng numpy thì: pip install numpy
import numpy as np

In [3]:
# thử tạo 1 list numpy
python_list = ([1,2,3,4,5])

#chuyển đổi danh sách trên thành numpy list
numpy_list = np.array(python_list)
type(numpy_list)

numpy.ndarray

In [4]:
# list trong python có thể hỗ trợ nhiều loại dữ liệu trong list
my_list = [1, "chào", True, 2.0]

In [5]:
my_list = [1,2,3,4.5]
np_list = np.array(my_list)
np_list

array([1. , 2. , 3. , 4.5])

In [6]:
# chuyển đổi kiểu dữ liệu 
np_list_int = np_list.astype(int)
np_list_int

array([1, 2, 3, 4])

In [7]:
# accessing và indexing
x = np.array([1,2,3,4,5,6,7,8])# np.array(range(1,9))


In [8]:
x[3]

np.int64(4)

In [9]:
# lấy nhiều hơn 1 phần tử
# công thức [start:end:step]
x[0:3]

array([1, 2, 3])

In [10]:
# lấy từ 3 - 8 theo 3 cách
# cacah 1
x[2:8]


array([3, 4, 5, 6, 7, 8])

In [11]:
# cách 2
x[2:]

array([3, 4, 5, 6, 7, 8])

In [12]:
# cách 3- không đúng
x[2:-1]

array([3, 4, 5, 6, 7])

In [13]:
# lấy số 3 vầ số 5
x[2], x[4]
x[2:5:2]

array([3, 5])

In [14]:
# đặt danh sách các index muốn truy cập
x[[2,4]]

array([3, 5])

In [15]:
data = [[1,2], [3,4], [5,6]]
np_list = np.array(data)
np_list

array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
# lấy số 2 
np_list[0,1]

np.int64(2)

In [17]:
# lấy số 6
np_list[2,1]

np.int64(6)

In [18]:
# layass 3 4 5 6 
np_list[1:, :]

array([[3, 4],
       [5, 6]])

In [19]:
# cách 2
np_list[[1,2]]


array([[3, 4],
       [5, 6]])

In [20]:
# cách3
np_list[1:3]

array([[3, 4],
       [5, 6]])

In [21]:
#cách 4
np_list[-2:]

array([[3, 4],
       [5, 6]])

In [22]:
# lấy 1 3 5 
np_list[:,0]

array([1, 3, 5])

In [23]:
np_list[::2,0]

array([1, 5])

In [24]:
x = [[1,2,3,4],
        [5,6,7,8],
        [9,10,11,12],
        [13,14,15,16]
]
np_list = np.array(x)
np_list

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [25]:
# layass 2 6 10 14
np_list[:,1]


array([ 2,  6, 10, 14])

In [26]:
# layass 7 và 11
np_list[1:3,2]

array([ 7, 11])

In [27]:
# lấy 4 7 10
np_list[[0,1,2],[3,2,1]]

array([ 4,  7, 10])

In [28]:
# lấy 16 15 14 13
np_list[[3,3,3,3],[3,2,1,0]]
np_list[-1, ::-1]

array([16, 15, 14, 13])

In [29]:
np_list[-1, -1::-1]


array([16, 15, 14, 13])

# BTVN thú vị

cho ma trận = 
# [[99,99,99],
# [99,99,99],
# [99,99,99]]

- hãy tưởng tượng ô 99 trống 
- giả sử  0 là o
- giả sử 1 là x
- lấy đầu vào từ phía x và phí o luôn phiên 
- Nếu đầu vào từ phía X là (0,0)
- ma trận sẽ trở thành 
# [x,99,99]
# [99,99,99]
# [99,99,99]
- nếu đầu vào từ phía o cũng là (0,0)
- thông báo nhập lại 
- nếu không thì điền vào ma trận

- thử thách: nếu người đầu tiên có 3 phần tử liên tiếp thì dùng trò chơi


In [51]:
def in_ma_tran(matrix):
    """Hàm hiển thị ma trận để dễ quan sát"""
    for row in matrix:
        display_row = []
        for cell in row:
            if cell == 1: display_row.append('X')
            elif cell == 0: display_row.append('O')
            else: display_row.append('.') # Thay 99 bằng dấu chấm cho dễ nhìn
        print(" | ".join(display_row))
    print("-" * 10)

def kiem_tra_thang(m):
    """Kiểm tra xem có ai thắng chưa"""
    # Kiểm tra hàng và cột
    for i in range(3):
        if m[i][0] == m[i][1] == m[i][2] != 99: return True # Hàng ngang
        if m[0][i] == m[1][i] == m[2][i] != 99: return True # Cột dọc
    
    # Kiểm tra 2 đường chéo
    if m[0][0] == m[1][1] == m[2][2] != 99: return True
    if m[0][2] == m[1][1] == m[2][0] != 99: return True
    
    return False

# 1. Khởi tạo ma trận ban đầu
matrix = [
    [99, 99, 99],
    [99, 99, 99],
    [99, 99, 99]
]

luot_cua_X = True # Biến đánh dấu lượt đi (True là X, False là O)
so_buoc_di = 0

print("--- TRÒ CHƠI TIC-TAC-TOE ---")
in_ma_tran(matrix)

# 2. Vòng lặp trò chơi
while so_buoc_di < 9:
    nguoi_choi = "X" if luot_cua_X else "O"
    gia_tri = 1 if luot_cua_X else 0
    
    print(f"Lượt của {nguoi_choi}:")
    try:
        hang = int(input("Nhập hàng (0, 1, 2): "))
        cot = int(input("Nhập cột (0, 1, 2): "))
        
        # Kiểm tra nếu nhập ngoài phạm vi
        if hang < 0 or hang > 2 or cot < 0 or cot > 2:
            print("Tọa độ không hợp lệ, vui lòng nhập từ 0 đến 2!")
            continue

        # 3. Kiểm tra ô trống (giá trị 99)
        if matrix[hang][cot] != 99:
            print("Ô này đã có người đi rồi! Vui lòng nhập lại.")
            continue
        
        # Điền vào ma trận
        matrix[hang][cot] = gia_tri
        in_ma_tran(matrix)
        so_buoc_di += 1
        
        # 4. Kiểm tra điều kiện thắng
        if kiem_tra_thang(matrix):
            print(f"CHÚC MỪNG! Người chơi {nguoi_choi} đã thắng!")
            break
            
        # Đổi lượt
        luot_cua_X = not luot_cua_X
        
    except ValueError:
        print("Vui lòng chỉ nhập số nguyên!")

if so_buoc_di == 9 and not kiem_tra_thang(matrix):
    print("Hòa rồi!")

--- TRÒ CHƠI TIC-TAC-TOE ---
. | . | .
. | . | .
. | . | .
----------
Lượt của X:
Vui lòng chỉ nhập số nguyên!
Lượt của X:
Vui lòng chỉ nhập số nguyên!
Lượt của X:
Vui lòng chỉ nhập số nguyên!
Lượt của X:
X | . | .
. | . | .
. | . | .
----------
Lượt của O:
X | O | .
. | . | .
. | . | .
----------
Lượt của X:
X | O | X
. | . | .
. | . | .
----------
Lượt của O:
Ô này đã có người đi rồi! Vui lòng nhập lại.
Lượt của O:
Ô này đã có người đi rồi! Vui lòng nhập lại.
Lượt của O:
X | O | X
O | . | .
. | . | .
----------
Lượt của X:
X | O | X
O | . | X
. | . | .
----------
Lượt của O:
Ô này đã có người đi rồi! Vui lòng nhập lại.
Lượt của O:
X | O | X
O | O | X
. | . | .
----------
Lượt của X:
Ô này đã có người đi rồi! Vui lòng nhập lại.
Lượt của X:
Ô này đã có người đi rồi! Vui lòng nhập lại.
Lượt của X:
X | O | X
O | O | X
. | X | .
----------
Lượt của O:
X | O | X
O | O | X
O | X | .
----------
Lượt của X:
Ô này đã có người đi rồi! Vui lòng nhập lại.
Lượt của X:
X | O | X
O | O | X
O | X | X

# BTVN 2
cho y = [[1,2,3],[4,5,6],[7,8,9]]

- lấy 4 5 6
- lấy 2, 5
- lấy 3,4
- lấy 9,6,3


In [ ]:
y = [
    [1, 2, 3],  
    [4, 5, 6],  
    [7, 8, 9]   
]

In [40]:
ket_qua_1 = y[1]
ket_qua_1

[4, 5, 6]

In [41]:
ket_qua_2 = [y[0][1], y[1][1]]
ket_qua_2

[2, 5]

In [42]:
ket_qua_3 = [y[0][2], y[1][0]]
ket_qua_3

[3, 4]

In [43]:
ket_qua_4 = [y[2][2], y[1][2], y[0][2]]
ket_qua_4

[9, 6, 3]

VD

In [30]:
np_x = np.arange(10)
np_x


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np_x % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [32]:
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
idx = [True, True,  True, False,  True, True,  True, False,  True, False]
np_x[idx]

array([0, 1, 2, 4, 5, 6, 8])

In [34]:
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
cond1 = np_x % 2 != 0
cond2 = np_x < 5
cond3 = np_x > 0

np_x[cond1 & cond2 | cond3]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# BTVN 3

# Cho x  = [[1,2,3,4,5,6,7,8,9,10]]

- xuất ra các giá trị chẵn sử dụng if
- xuất ra các giá trị chẵn sử dụng list comprehension


In [44]:
x = [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]]

In [46]:
print("Các số chẵn dùng if:")

# Duyệt qua từng phần tử trong danh sách con x[0]
for so in x[0]:
    if so % 2 == 0:
        print(so)

Các số chẵn dùng if:
2
4
6
8
10


In [47]:
# Tạo danh sách các số chẵn
so_chan = [so for so in x[0] if so % 2 == 0]

print("Các số chẵn (dùng List Comprehension):")
so_chan

Các số chẵn (dùng List Comprehension):


[2, 4, 6, 8, 10]

# BTVN4
- tạo 1 mảng numpy có kích thức 150 x 5. giả sử mảng này chứa 150 mẫu dữ liệu 
- của sinh vienen  bao gồm chiều cao cân nặng tuổi , lương và điểm trung bình
- tách mảng dựa trên 4 cột đầu tiên thành 1 biến có tên là x và cột cuối cùng thành y
- tách mảng X thành X train X test trong đó X train chứa 70% dữ liệu và tách y thành y train và y test trong đó y train chứa 70% dữ leieuj
- tạo 10 tập dữ liệu không chồng chéo nhau 

In [ ]:
import numpy as np

# --- 1. Tạo mảng Numpy 150x5 ---
# Giả lập dữ liệu ngẫu nhiên để minh họa
# Cấu trúc: [Chiều cao, Cân nặng, Tuổi, Lương, Điểm TB]
# np.random.rand tạo số thực từ 0 đến 1, nhân lên để có giá trị thực tế hơn 
data = np.random.rand(150, 5) 

# In kích thước để kiểm tra
print(f"Kích thước dữ liệu gốc: {data.shape}") 
print("-" * 30)

# --- 2. Tách X (4 cột đầu) và y (cột cuối) ---
# Dùng kỹ thuật Slicing (cắt lát): [hàng, cột]
# : có nghĩa là lấy tất cả hàng
# :4 nghĩa là lấy từ cột 0 đến sát cột 4 (0, 1, 2, 3)
# 4 nghĩa là chỉ lấy cột chỉ số 4 (cột cuối cùng)

X = data[:, :4]  
y = data[:, 4]   

print(f"Kích thước X: {X.shape}")
print(f"Kích thước y: {y.shape}")
print("-" * 30)

# --- 3. Tách Train (70%) và Test (30%) ---
# Tính chỉ số cắt (index)
# 150 mẫu * 70% = 105 mẫu
split_index = int(150 * 0.7)

# Lưu ý: Trong thực tế nên xáo trộn (shuffle) dữ liệu trước khi cắt
# np.random.shuffle(data) # Bỏ comment dòng này nếu muốn xáo trộn

# Cắt dữ liệu
X_train = X[:split_index]       # Lấy từ đầu đến 105
X_test = X[split_index:]        # Lấy từ 105 đến hết

y_train = y[:split_index]
y_test = y[split_index:]

print(f"Kích thước X_train: {X_train.shape} (70%)")
print(f"Kích thước X_test:  {X_test.shape} (30%)")
print(f"Kích thước y_train: {y_train.shape}")
print(f"Kích thước y_test:  {y_test.shape}")
print("-" * 30)

# --- 4. Tạo 10 tập dữ liệu không chồng chéo ---
# Dùng hàm array_split để chia đều mảng thành các phần
# 150 mẫu / 10 = 15 mẫu mỗi tập
# folds là một danh sách chứa 10 mảng numpy con

folds = np.array_split(data, 10)

print(f"Số lượng tập con: {len(folds)}")
print(f"Kích thước mỗi tập con: {folds[0].shape}")
# Kiểm tra thử tập đầu tiên
# print(folds[0])

Kích thước dữ liệu gốc: (150, 5)
------------------------------
Kích thước X: (150, 4)
Kích thước y: (150,)
------------------------------
Kích thước X_train: (105, 4) (70%)
Kích thước X_test:  (45, 4) (30%)
Kích thước y_train: (105,)
Kích thước y_test:  (45,)
------------------------------
Số lượng tập con: 10
Kích thước mỗi tập con: (15, 5)
